# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=arm
CONFIG_SOFTMMU=yes
TARGET_XML_FILES= /home/jinho/xenrepo/packages/xen-4.1.2/tools/ioemu-qemu-xen/gdb-xml/arm-core.xml /home/jinho/xenrepo/packages/xen-4.1.2/tools/ioemu-qemu-xen/gdb-xml/arm-vfp.xml /home/jinho/xenrepo/packages/xen-4.1.2/tools/ioemu-qemu-xen/gdb-xml/arm-vfp3.xml /home/jinho/xenrepo/packages/xen-4.1.2/tools/ioemu-qemu-xen/gdb-xml/arm-neon.xml
CONFIG_SOFTFLOAT=yes
