# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=ppc64
TARGET_ABI_DIR=ppc
TARGET_ARCH2=ppc64abi32
TARGET_WORDS_BIGENDIAN=yes
CONFIG_USER_ONLY=yes
CONFIG_LINUX_USER=yes
TARGET_XML_FILES= /home/jinho/xenrepo/packages/xen-4.1.2/tools/ioemu-qemu-xen/gdb-xml/power64-core.xml /home/jinho/xenrepo/packages/xen-4.1.2/tools/ioemu-qemu-xen/gdb-xml/power-fpu.xml /home/jinho/xenrepo/packages/xen-4.1.2/tools/ioemu-qemu-xen/gdb-xml/power-altivec.xml /home/jinho/xenrepo/packages/xen-4.1.2/tools/ioemu-qemu-xen/gdb-xml/power-spe.xml
CONFIG_SOFTFLOAT=yes
